CREATE TABLE bracelets (
    id BIGSERIAL PRIMARY KEY,
    nfcuid VARCHAR(100) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    state VARCHAR(20) CHECK (state IN ('LINKED', 'BLOCKED', 'FREE')) NOT NULL,
    link_date TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_bracelet_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
