CREATE TABLE administrators (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL
    creation_date TIMESTAMP NOT NULL DEFAULT NOW()
);
