# Entorno de la aplicación
spring.profiles.active=dev

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nfconsumerdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Configuración de JPA/Hibernate /// Validate == No modifica el schema (Usar flyway)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=swagger-ui.html



# Base path para el api rest
spring.mvc.servlet.path=/api/v1

# Configuración para el manejo de errores
#server.error.whitelabel.enabled=false
#server.error.path=/error

#JWT config
#Ojo, secret-key no se debe hacer pública si no se vulnera la seguridad.
application.security.jwt.secret-key=ml1MlxSL5INpF9DVs4ixYxUwy6iN/P3pEm50uGuZ9rQ=
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Security temporal
spring.security.enabled=true
